apiVersion: v1
kind: Service
metadata:
  name: app2-service
  labels:
    name: app2-service
    app: app2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: app2-pod
    app: myapp-2